name: test

on:
  release:
    types: [created]
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'test'  

jobs:

  build:
    strategy:
      matrix:
        java: [ '8', '16' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}

    - name: Compile and test
      run: mvn -B compile test --file pom.xml
